---
platform: linux

inputs:
- name: git-storagetests
  path: gopath/src/github.com/anothermemory/storagetests
- name: git-storage
  path: gopath/src/github.com/anothermemory/storage
- name: git-unit
  path: gopath/src/github.com/anothermemory/unit
- name: git-id
  path: gopath/src/github.com/anothermemory/id
- name: git-clock
  path: gopath/src/github.com/anothermemory/clock

run:
  path: sh
  args:
    - -exc
    - |
      export GOPATH=$(pwd)/gopath:${GOPATH} && \
      cd gopath/src/github.com/anothermemory/storagetests && \
      go version && \
      zb build && \
      zb lint -f --exclude=/usr/local/go && \
      go test -v ./...